version = 0.1
[default.deploy.parameters]
stack_name = "taylor-swift-ticketing-stack"
resolve_s3 = true
s3_prefix = "taylor-swift-ticketing-stack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" OwnerAlias=\"minholee\" EmailAddress=\"miniholee@amazon.com\" SpringClean=\"yes\""
image_repositories = []
